import React from 'react';
import { Brain, Sparkles, ArrowRight, CheckCircle2, AlertTriangle, PlayCircle } from 'lucide-react';
import { MOCK_BLUEPRINT } from '../data/defaultUserData';

export default function AIBlueprint({ userProfile }) {
  
  // Adapt blueprint career target dynamically
  const career = userProfile.personalInfo.targetCareer || MOCK_BLUEPRINT.goal;
  const currentRole = userProfile.personalInfo.profession || MOCK_BLUEPRINT.currentRole;

  // Let's customize gap values based on selected careers
  const isCustomCareer = career !== 'AI Engineer';
  const gaps = isCustomCareer ? [
    { skill: `Core ${career} Competency`, current: 20, target: 90, gap: 70 },
    { skill: "Strategic Problem Solving", current: 30, target: 85, gap: 55 },
    { skill: "Portfolio & Applied Experience", current: 15, target: 90, gap: 75 },
    { skill: "Domain Frameworks & Tools", current: 25, target: 80, gap: 55 },
    { skill: "Collaboration & Communication", current: 50, target: 85, gap: 35 }
  ] : MOCK_BLUEPRINT.gapAnalysis;

  const roadmap = isCustomCareer ? [
    { year: "2026", focus: `Foundational Knowledge & Core ${career} Skills`, status: "In Progress", details: `Learn essential concepts, master industry tools, and construct 3 small projects. Allocate 2 hours daily.` },
    { year: "2027", focus: "Applied Projects & Professional Certifications", status: "Upcoming", details: "Validate skills with certified credentials, engage in community guilds, and secure a junior role/internship." },
    { year: "2028", focus: "Advanced Competencies & Systems Integration", status: "Upcoming", details: "Build complex end-to-end architectures, optimize performance speeds, and lead collaborative sprints." },
    { year: "2029", focus: "Elite Placement Preparation & Industry Alignment", status: "Upcoming", details: "Complete technical mock interviews, optimize resume keywords, and transition into senior roles." }
  ] : MOCK_BLUEPRINT.roadmap;

  return (
    <div style={{ padding: '30px' }}>
      
      {/* Module Title */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '32px' }}>
        <div>
          <h1 style={{ fontSize: '2rem', fontWeight: '800', display: 'flex', alignItems: 'center', gap: '12px' }}>
            <Brain size={28} color="#8B5CF6" />
            <span>AI Life Blueprint</span>
          </h1>
          <p style={{ color: '#94A3B8', fontSize: '0.95rem', marginTop: '4px' }}>
            Personal strategy generated by Gemini. Gap analysis and chronological roadmap.
          </p>
        </div>
        <div className="item-badge badge-accent" style={{ padding: '8px 16px', fontSize: '0.9rem' }}>
          Target: {career}
        </div>
      </div>

      {/* Top Gap Analysis Panel */}
      <div className="dashboard-grid" style={{ marginBottom: '32px' }}>
        
        {/* Gap Chart Visual (7 cols) */}
        <div className="glass-panel" style={{ gridColumn: 'span 7', padding: '24px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
            <h3 style={{ fontSize: '1.1rem', fontWeight: '700' }}>Skill Gap Analysis</h3>
            <span style={{ fontSize: '0.75rem', color: '#94A3B8' }}>Current vs Industry standard target</span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '18px' }}>
            {gaps.map((g, i) => (
              <div key={i}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', marginBottom: '6px' }}>
                  <span style={{ fontWeight: '500' }}>{g.skill}</span>
                  <span style={{ color: '#94A3B8' }}>
                    Current: <strong style={{ color: 'white' }}>{g.current}%</strong> / Target: <strong style={{ color: '#8B5CF6' }}>{g.target}%</strong>
                  </span>
                </div>
                
                {/* Visual bar graph representation */}
                <div style={{ position: 'relative', width: '100%', height: '12px', background: 'rgba(255,255,255,0.03)', borderRadius: '6px', overflow: 'hidden' }}>
                  {/* Current Bar */}
                  <div style={{
                    position: 'absolute', top: 0, left: 0, height: '100%', width: `${g.current}%`,
                    background: 'linear-gradient(90deg, #2563EB, #8B5CF6)', borderRadius: '6px', zIndex: 2
                  }} />
                  {/* Target Marker border */}
                  <div style={{
                    position: 'absolute', top: 0, left: 0, height: '100%', width: `${g.target}%`,
                    background: 'rgba(139,92,246,0.1)', borderRight: '2px dashed #8B5CF6', zIndex: 1
                  }} />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Strategic Analysis summary (5 cols) */}
        <div className="glass-panel" style={{ gridColumn: 'span 5', padding: '24px', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
          <div>
            <span style={{ fontSize: '0.75rem', fontWeight: '800', color: '#C084FC', letterSpacing: '1px', textTransform: 'uppercase' }}>Gemini Gap Diagnosis</span>
            <h3 style={{ fontSize: '1.2rem', fontWeight: '700', marginTop: '6px', marginBottom: '16px' }}>The transition from {currentRole}</h3>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: '14px', fontSize: '0.88rem', color: '#94A3B8', lineHeight: '1.5' }}>
              <p>
                ⚠️ <strong>Key Friction Point:</strong> The largest skill gap resides in <strong>Practical Portfolio Projects ({isCustomCareer ? '75%' : '60%'} deficiency)</strong>. Theoretical knowledge from college lectures is insufficient.
              </p>
              <p>
                📈 <strong>Leverage Area:</strong> Your communication skills sit at {isCustomCareer ? '50%' : '65%'}, providing a strong foundation for technical writing and collaborative team sprints.
              </p>
              <p>
                🚀 <strong>Primary Commandment:</strong> Prioritize structural development of projects. Move beyond tutorial reading and start building custom code apps immediately.
              </p>
            </div>
          </div>

          <div style={{
            background: 'rgba(37,99,235,0.08)', border: '1px solid rgba(37,99,235,0.15)',
            padding: '12px 16px', borderRadius: '10px', marginTop: '16px'
          }}>
            <span style={{ fontSize: '0.75rem', color: '#60A5FA', fontWeight: '700', display: 'block' }}>ACTION PLAN TRIGGER</span>
            <p style={{ fontSize: '0.82rem', color: '#E2E8F0', marginTop: '4px' }}>
              We scheduled <strong>"Solve LeetCode DSA Tree questions"</strong> on your daily workspace planner to begin addressing this roadmap track.
            </p>
          </div>
        </div>

      </div>

      {/* Interactive Roadmap timeline */}
      <div className="glass-panel" style={{ padding: '30px' }}>
        <h3 style={{ fontSize: '1.2rem', fontWeight: '700', marginBottom: '24px' }}>Chronological Career Execution Roadmap</h3>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '30px', position: 'relative' }}>
          
          {/* Timeline center line indicator */}
          <div style={{
            position: 'absolute', top: '20px', bottom: '20px', left: '16px',
            width: '2px', background: 'rgba(255,255,255,0.05)'
          }} />

          {roadmap.map((track, idx) => (
            <div key={idx} style={{ display: 'flex', gap: '20px', position: 'relative' }}>
              {/* Point dot indicator */}
              <div style={{
                width: '34px', height: '34px', borderRadius: '50%',
                background: track.status === 'In Progress' ? 'linear-gradient(135deg, #2563EB, #8B5CF6)' : '#1E293B',
                border: track.status === 'In Progress' ? 'none' : '2px solid rgba(255,255,255,0.08)',
                zIndex: 2, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0
              }}>
                <div style={{
                  width: '12px', height: '12px', borderRadius: '50%',
                  background: track.status === 'In Progress' ? 'white' : '#94A3B8'
                }} />
              </div>

              {/* Roadmap Content */}
              <div style={{ flex: 1, padding: '16px 20px', background: 'rgba(255,255,255,0.01)', border: '1px solid rgba(255,255,255,0.04)', borderRadius: '14px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '8px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <span style={{ fontSize: '1.25rem', fontWeight: '800', color: track.status === 'In Progress' ? '#8B5CF6' : 'white' }}>{track.year}</span>
                    <h4 style={{ fontSize: '1rem', fontWeight: '700', color: '#E2E8F0' }}>{track.focus}</h4>
                  </div>
                  <span className={`item-badge ${track.status === 'In Progress' ? 'badge-primary' : 'badge-accent'}`} style={{ fontSize: '0.65rem' }}>
                    {track.status}
                  </span>
                </div>
                <p style={{ color: '#94A3B8', fontSize: '0.88rem', lineHeight: '1.5', marginTop: '10px' }}>
                  {track.details}
                </p>
              </div>
            </div>
          ))}

        </div>
      </div>

    </div>
  );
}
